#Build stage
#Node base image
FROM node:22.17.1-alpine as build

#Set working directory 
WORKDIR /app

#Copy package.json and package-lock.json
COPY package.json ./
RUN npm install

#COPY all files to container
COPY . .

RUN npm run build

#-------------------------
#Production stage
FROM nginx:alpine as prod

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]