# Production stage
FROM node:22.17.1-alpine as prod

WORKDIR /app

# Copy both files before installing
COPY package*.json ./

# Install dependencies including dotenv
RUN npm install

# Then copy the remaining source code
COPY . .

CMD ["node", "server.js"]

